inventory/urls.py
"""Inventory App URLs"""
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from inventory.views import (
    DashboardView,
    LogoutView,
    ProfileView,
    EditProfileView,
    ItemsListView,
    AddItemView,
    EditItemView,
    RequestItemView,
    ProvisionListView,
    ReturnItemView,
    ProvisionItemView,
    ProvisionByRequestView,
    EditItemListView,
    LoadMoreView, ImageUploadView, UserAutocompleteView,
    ItemAutocompleteView, ReportView, ReportAjaxView, LoginFormView)
from inventory.decorators import (
    admin_required,
    anonymous_required
)


urlpatterns = patterns(
    '',

    # urls available to both users and admins
    url(
        r'^$',
        TemplateView.as_view(template_name='home.html'),
        name="home"
    ),
    url(
        r'^login/$',
        anonymous_required(
            LoginFormView.as_view(),
            redirect_to='dashboard'
        ),
        name="login"
    ),
    url(
        r'^logout/$',
        LogoutView.as_view(),
        name="logout"
    ),
    url(
        r'^dashboard/$',
        login_required(
            DashboardView.as_view()
        ),
        name="dashboard"
    ),
    url(
        r'^profile/$',
        login_required(
            ProfileView.as_view()
        ),
        name="profile"
    ),
    url(
        r'^profile/edit/$',
        login_required(
            EditProfileView.as_view()
        ),
        name="edit_profile"
    ),
    url(
        r'^items/$',
        login_required(
            ItemsListView.as_view()
        ),
        name="items_list"
    ),

    # urls for admin only
    url(
        r'^items/add/$',
        admin_required(
            AddItemView.as_view()
        ),
        name="add_item"
    ),
    url(
        r'^items/edit/$',
        admin_required(
            EditItemListView.as_view()
        ),
        name='edit_item_list'
    ),
    url(
        r'^items/edit/(?P<pk>[\d]+)/$',
        admin_required(
            EditItemView.as_view()
        ),
        name='edit_item'
    ),
    url(
        r'^items/return/$',
        admin_required(
            ProvisionListView.as_view()
        ),
        name='provision_list'
    ),
    url(
        r'^items/return/(?P<pk>[\d]+)/$',
        admin_required(
            ReturnItemView.as_view()
        ),
        name='return_item'
    ),
    url(
        r'^items/provision/$',
        admin_required(
            ProvisionItemView.as_view()
        ),
        name='provision_item'
    ),
    url(
        r'^items/provision/(?P<pk>[\d]+)/$',
        admin_required(
            ProvisionByRequestView.as_view()
        ),
        name='provision_by_request'
    ),
    url(
        r'^report/$',
        admin_required(
            ReportView.as_view()
        ),
        name='report'
    ),
    url(
        r'^report/ajax/$',
        admin_required(
            ReportAjaxView.as_view()
        ),
        name='report_ajax'
    ),

    # urls for user role (but admin can also access)
    url(
        r'^request/$',
        login_required(
            RequestItemView.as_view()
        ),
        name='request_item'
    ),

    # urls to handle AJAX requests
    url(
        r'^ajax/load_more/$',
        login_required(
            LoadMoreView.as_view()
        ),
        name="load_more_ajax"
    ),
    url(
        r'^ajax/upload_image/$',
        login_required(
            ImageUploadView.as_view()
        ),
        name="image_upload_ajax"
    ),
    url(
        r'^ajax/user_autocomplete/$',
        admin_required(
            UserAutocompleteView.as_view(),
        ),
        name="user_autocomplete_ajax"
    ),
    url(
        r'^ajax/item_autocomplete/$',
        admin_required(
            ItemAutocompleteView.as_view(),
        ),
        name="item_autocomplete_ajax"
    ),
)

project_name/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from project_name.settings import MEDIA_ROOT, MEDIA_URL

admin.autodiscover()

urlpatterns = patterns('',
    # Admin panel and documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(
        r'^admin/',
        include(admin.site.urls)
    ),
    url(
        r'^',
        include('inventory.urls')
    ),
)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

inventory/models.py
"""Inventory App Models"""
import os
import time

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.core.validators import RegexValidator
from django.db import models


# REGEX used
FIRST_NAME_REGEX = RegexValidator(
    regex=r'^[A-Za-z]([a-zA-Z ,\'\.]*)$',
    message="Invalid first name entered"
)
LAST_NAME_REGEX = RegexValidator(
    regex=r'^[a-zA-Z]+$',
    message="Invalid last name entered"
)
PHONE_REGEX = RegexValidator(
    regex=r'^\d{10,10}$',
    message="Please enter a valid phone number. Only 10 digits allowed."
)
ID_NUMBER_REGEX = RegexValidator(
    regex=r'^[a-zA-Z0-9]*$',
    message="Enter a valid id number. Only alphabets and digits allowed."
)


class UserManager(BaseUserManager):
    """User Manager for custom User Model"""

    def _create_user(self, email, password, is_superuser, **extra_fields):
        """Save user in db"""

        if not email:
            raise ValueError('Email cannot be blank')

        email = self.normalize_email(email)
        user = self.model(
            email=email,
            is_superuser=is_superuser,
            **extra_fields
        )
        user.set_password(password)
        user.save(self._db)
        return user

    def create_user(self, email, password, **extra_fields):
        """Create a user"""

        return self._create_user(
            email,
            password,
            False,
            **extra_fields
        )

    def create_superuser(self, email, password, **extra_fields):
        """Create a superuser"""

        return self._create_user(
            email,
            password,
            True,
            **extra_fields
        )


def get_image_path(instance, filename):
    """Generate a path for new image"""

    # Save extension of image
    extension = os.path.splitext(filename)[1]

    # Generate filename and path
    filename = str(int(round(time.time() * 1000))) + str(extension)
    return os.path.join(filename)


class User(AbstractBaseUser):
    """Custom user model"""

    email = models.EmailField(
        'email address',
        unique=True,
    )

    first_name = models.CharField(
        max_length=50,
        null=True,
        validators=[FIRST_NAME_REGEX]
    )

    last_name = models.CharField(
        max_length=50,
        null=True,
        validators=[LAST_NAME_REGEX]
    )

    phone = models.CharField(
        validators=[PHONE_REGEX],
        max_length=10
    )

    address = models.TextField(
        null=True,
    )

    id_number = models.CharField(
        max_length=10,
        validators=[ID_NUMBER_REGEX],
        null=True,
        unique=True
    )

    image = models.ImageField(
        upload_to=get_image_path,
        blank=True,
        null=True
    )

    is_admin = models.BooleanField(
        default=False
    )

    is_superuser = models.BooleanField(
        default=False
    )

    USERNAME_FIELD = 'email'
    objects = UserManager()

    def __unicode__(self):
        """unicode method"""
        return '{0} {1} ({2})'.format(self.first_name, self.last_name,
                                      self.email) if self.first_name and self.last_name else self.email

    @property
    def is_staff(self):
        """is staff method"""
        return self.is_superuser

    def has_perm(self, perm, obj=None):
        """has permissions"""
        return True

    def has_module_perms(self, app_label):
        """has module permissions"""
        return True

    def get_short_name(self):
        """get short name"""
        return self.first_name

    def get_full_name(self):
        """get full name"""
        return self.first_name

    def delete_image(self):
        """delete profile image from file system"""
        try:
            os.remove(self.image.path)
        except:
            pass


class Item(models.Model):
    """Model for inventory items"""

    name = models.CharField(
        max_length=50,
        unique=True,
    )

    description = models.TextField(
        blank=True,
        null=True
    )

    returnable = models.BooleanField()

    quantity = models.IntegerField(
        default=1,
    )

    def __unicode__(self):
        """unicode method"""
        return self.name


class Provision(models.Model):
    """Model for provision/issues"""

    item = models.ForeignKey(Item)
    user = models.ForeignKey(User)

    timestamp = models.DateTimeField(
        auto_now=True
    )

    approved = models.BooleanField(
        default=False
    )

    approved_on = models.DateTimeField(
        null=True,
    )

    return_by = models.DateTimeField(
        null=True,
    )

    quantity = models.IntegerField(
        null=True,
    )

    returned = models.BooleanField(
        default=False
    )

    returned_on = models.DateTimeField(
        null=True,
    )

    request_by_user = models.BooleanField(
        default=False
    )

inventory/templates/add_item.html
{% extends 'base.html' %}

{% block title %}Inventory Management|Add Item{% endblock %}

{% if messages %}
    {% for message in messages %}
        {{ message }}
    {% endfor %}
{% endif %}

{% block content %}
    <h1>New Item</h1>
    <form method="POST" class="item-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
        <a href="{% url 'dashboard' %}" class="btn btn-default">Cancel</a>
    </form>
{% endblock %}

inventory/templates/base.html
{% load staticfiles %}
{% load custom_tags %}
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">
        <link rel="stylesheet" href="{% static 'css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'css/jquery.dataTables.min.css' %}"/>
        <link href='https://fonts.googleapis.com/css?family=Lato:400,700,400italic,300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
        <script src="{% static 'js/pace.min.js' %}"></script>
    </head>
    <body>

    {# Container for alert messages #}
    <div class="alert-container flash animated">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-dismissable alert-{{ message.tags }}" role="alert">
                                    {{ message }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                </div>
                            {% endfor %}
                        {% endif %}
                </div>
            </div>
        </div>
    </div> {# end alert-container #}

    {# Navigation start #}
    <div class="navbar navbar-fixed-top navbar-inverse">
        <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% if request.user.is_authenticated %}{% url 'dashboard' %}{% else %}{% url 'login' %}{% endif %}">Inventory Management</a>
            </div>

            {% if request.user.is_authenticated %}

            <div class="collapse navbar-collapse" id="navbar">

                <ul class="nav navbar-nav navbar-right">
                {% if not request.user.is_admin %}

                    <li class="{% active 'dashboard' %}">
                        <a href="{% url 'dashboard' %}">Dashboard</a>
                    </li>
                    <li class="{% active 'items_list' %}">
                        <a href="{% url 'items_list' %}">Items List</a>
                    </li>
                    <li class="{% active 'request_item' %}">
                        <a href="{% url 'request_item' %}">Request Item</a>
                    </li>
                    <li class="dropdown {% active '^/profile/' %}">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Profile
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'profile' %}">View Profile</a></li>
                            <li><a href="{% url 'edit_profile' %}">Edit Profile</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li class="dropdown {% active 'dashboard' %}">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">{% role_prefix 'Admin ' 'User ' %}Dashboard
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                          <li><a href="{% url 'dashboard' %}">Admin Dashboard</a></li>
                          <li><a href="{% url 'dashboard' %}?user=True">User Dashboard</a></li>
                        </ul>
                    </li>
                    <li class="dropdown {% active 'items_list' 'add_item' 'edit_item_list' 'edit_item' %}">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Manage Items
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'items_list' %}">Items List</a></li>
                            <li><a href="{% url 'add_item' %}">Create Item</a></li>
                            <li><a href="{% url 'edit_item_list' %}">Edit Item</a></li>
                        </ul>
                    </li>
                    <li class="dropdown {% active 'provision_list' 'provision_item' 'request_item' 'return_item' %}">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Manage Provisions
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'provision_item' %}">Provision Item</a></li>
                            <li><a href="{% url 'provision_list' %}">Return Item</a></li>
                            <li><a href="{% url 'request_item' %}">Request Item</a></li>
                        </ul>
                    </li>
                    <li class="dropdown {% active 'profile' 'edit_profile' %}">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Profile
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'profile' %}">View Profile</a></li>
                            <li><a href="{% url 'edit_profile' %}">Edit Profile</a></li>
                        </ul>
                    </li>
                    <li class="{% active 'report' %}"><a href="{% url 'report' %}">Report</a></li>
                    {% endif %}
                    <li>
                        <a href="{% url 'logout' %}">Logout</a>
                    </li>
                </ul>
            </div>
            {% endif %}
        </div>
    </div> {# end Navigation #}

    {# Content  Block for templates #}
    <div class="main-content container">
        {% block content %}
        {% endblock %}
    </div> {# end Content Block #}

    {# Footer Begin #}
    <footer>
        <div class="container">
            <div class="inner">
            {% if request.user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
                    <li><a href="{% url 'items_list' %}">Items</a></li>
                    <li><a href="{% url 'profile' %}">Profile</a></li>

                    {% if request.user.is_admin %}
                    <li><a href="{% url 'add_item' %}">Create Item</a></li>
                    <li><a href="{% url 'edit_item_list' %}">Edit Item</a></li>
                    <li><a href="{% url 'provision_item' %}">Provision Item</a></li>
                    <li><a href="{% url 'provision_list' %}">Return Item</a></li>
                    <li><a href="{% url 'report' %}">Report</a></li>
                    {% else %}
                    <li><a href="{% url 'request_item' %}">Request Item</a></li>
                    {% endif %}
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                </ul>
            {% endif %}
            </div>
        </div>
    </footer> {# end footer #}

    </body>
    <script src="{% static 'js/ajax.js' %}"></script>
</html>

inventory/templates/dashboard.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load custom_tags %}
{% static "images/default.jpg" as default_picture %}
{% block title %}Inventory Management|Dashboard{% endblock %}

{% block content %}

<div class="row">
    <div class="col-md-3">
        <div id="profile-sticker">
            <a class="fa fa-edit edit-profile-link" href="{% url 'edit_profile' %}" alt="Edit Profile"></a>
            <div class="dp-box" style="background-image: url('{% if user.image %}{{ user.image.url }}{%else %}{% static "images/default.jpg" %}{% endif %}'); background-size: cover; background-position: center;">
            </div>
            <div class="profile-info">
                <h4 class="profile-tabs name">{% if_data '(Not Available)' user.first_name user.last_name %}</h4>
                <h5 class="profile-tabs email">{{ user.email|truncatechars:30 }}</h5>

                <h6 class="profile-lower"><i class="fa fa-phone"></i> {% if_data '(Not Available)' user.phone %}</h6>
                <h6 class="profile-lower"><i class="fa fa-map-marker"></i> {% if_data '(Not Available)' user.address %}</h6>
                <h6 class="profile-lower"><i class="fa fa-user"></i> {% if_data '(Not Available)' user.id_number %}</h6>
            </div>
        </div>
    </div>

    <div class="col-md-9">
        <div class="table-container">
            <h1 class="custom-heading">Pending Requests</h1>
            <table class="table-striped table-bordered" id="pending_table">
                <tr>
                    <th>Item</th>
                    <th>Description</th>
                    <th>Request on</th>
                    {% if is_admin %}
                        <th>User</th>
                        <th>Link to provision</th>
                    {% endif %}
                </tr>
                {% for req in pending %}
                    <tr>
                        <td>{{ req.item.name }}</td>
                        <td>{{ req.item.description|truncatechars:30 }}</td>
                        <td>{{ req.timestamp|date:"d M y" }}</td>
                        {% if is_admin %}
                        <td>
                            {{ req.user }}
                        </td>
                        <td>
                            <a href="{% url 'provision_by_request' req.id %}">Provision Item</a>
                        </td>
                        {% endif %}

                    </tr>
                {% endfor %}
            </table>
            <div class="load_more_container">
                {% if pending_more %}
                    <a class="btn btn-default" href="#" id="load_more_pending" action="{% url 'load_more_ajax' %}">Load More</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="table-container">
            <h1 class="custom-heading">Approved Requests</h1>
            <table class="table-striped table-bordered" id="approved_table">
                <tr>
                    <th>Item</th>
                    <th>Description</th>
                    <th>Returnable</th>
                    <th>Return by date</th>
                    {% if is_admin %}
                    <th>User</th>
                    <th>Returned</th>
                    <th>Return Item</th>
                    {% endif %}

                </tr>
                {% for req in approved %}
                    <tr>
                        <td>{{ req.item.name }}</td>
                        <td>{{ req.item.description|truncatechars:100 }}</td>
                        <td>
                            {{ req.item.returnable|yesno:"Yes,No,Maybe" }}
                        </td>
                        <td>
                            {% if req.item.returnable %}
                                {{ req.return_by|date:"d M y" }}
                            {% else %}
                                N/A
                            {% endif %}
                        </td>

                        {% if is_admin %}

                        <td>{{ req.user }}</td>
                        <td>{% if req.item.returnable and req.item.returned %}
                                Yes
                            {% elif req.item.returnable and not req.item.returned %}
                                No
                            {% else %}
                                N/A
                            {% endif %}</td>
                        <td>{% if req.item.returnable and req.item.returned %}
                                Returned
                            {% elif req.item.returnable and not req.item.returned %}
                                <a href="{% url 'return_item' req.id %}">Mark Returned</a>
                            {% else %}
                                N/A
                            {% endif %}</td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </table>
            <div class="load_more_container">
                {% if approved_more %}
                    <a class="btn btn-default" href="#" id="load_more_approved" action="{% url 'load_more_ajax' %}">Load More</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

    <script>
        // Javascript variables
        var is_admin = {% if is_admin and not request.GET.user %}'True'{% else %}'False'{% endif %},
            provision_list_url = '{% url 'provision_list' %}',
            provision_item_url = '{% url 'provision_item' %}';
    </script>

{% endblock %}

inventory/templates/edit_item_list.html
{% extends 'base.html' %}
{% block title %}Inventory Management|Items Edit{% endblock %}
{% block content %}
    <h1>Select Item to Edit</h1>
    <table class="table-bordered table-striped">
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Returnable</th>
            <th>Quantity</th>
            <th>Action</th>
        </tr>
        {% for item in object_list %}
        <tr>
            <td>{{ item.name }}</td>
            <td>{{ item.description|truncatechars:80 }}</td>
            <td>{% if item.returnable %}Yes{% else %}No{% endif %}</td>
            <td>{{ item.quantity }}</td>
            <td><a href="{% url 'edit_item_list' %}{{ item.id }}">Edit Item</a></td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

inventory/templates/edit_profile.html
{% extends 'base.html' %}

{% block title %}Inventory Management|Edit Profile{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-6">
            <form class="form-vertical" role="form" action="" method="post" enctype="multipart/form-data" id="profile_update_form">
                {% csrf_token %}
                <h3>Edit Profile</h3>
                    {{ form.non_field_errors }}

                    <div class="form-group">
                        {{ form.first_name.errors }}
                        <label for="{{ form.first_name.id_for_label }}">First Name:</label>
                        {{ form.first_name }}
                    </div>

                    <div class="form-group">
                        {{ form.last_name.errors }}
                        <label for="{{ form.last_name.id_for_label }}">Last Name:</label>
                        {{ form.last_name }}
                    </div>

                    <div class="form-group">
                        {{ form.phone.errors }}
                        <label for="{{ form.phone.id_for_label }}">Phone:</label>
                        {{ form.phone }}
                    </div>

                    <div class="form-group">
                        {{ form.address.errors }}
                        <label for="{{ form.address.id_for_label }}">Address:</label>
                        {{ form.address }}
                    </div>

                    <div class="form-group">
                        {{ form.id_number.errors }}
                        <label for="{{ form.id_number.id_for_label }}">Id Number:</label>
                        {{ form.id_number }}
                    </div>

                    <div class="form-group" action="{% url 'image_upload_ajax' %}">
                        <label for="image">Image:</label>
                        <img id="profile_image" src="{% if form.instance.image %}{{ form.instance.image.url }}{% endif %}" alt=""/>
                        <br/>
                        <a href="#" id="image_clear">Clear</a>
                        <br/>
                        Change:
                        <input id="image" name="image" type="file">
                    </div>

                <button type="submit" class="save btn btn-default">Save</button>
                <a href="{% url 'profile' %}" class="btn btn-default">Cancel</a>
            </form>
        </div>
        <div class="col-md-6">
            <form class="form-vertical" role="form" action="" method="post">
                <h3>Change Password</h3>
                {% csrf_token %}
                {{ form2.as_p }}
                <button type="submit" class="save btn btn-default" name="change_password" value="True">Change</button>
            </form>
        </div>
    </div>
    <script>
        // Javascript variables
        var csrf = '{{ csrf_token }}';
    </script>


{% endblock %}

inventory/templates/image_test.html
{% extends 'base.html' %}

{% block title %}Inventory Management|Edit Profile{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-6">
            <form class="form-vertical" role="form" action="{% url 'image_upload_ajax' %}" method="post" enctype="multipart/form-data" id="profile_update_form">
                {% csrf_token %}
                <h3>Edit Profile</h3>
{#                    <div class="form-group" action="{% url 'image_upload_ajax' %}">#}
{#                        <input id="id_image" name="image" type="file">#}
{#                    </div>#}

                <input type="hidden" name="clear_image" value="True"/>

                <button type="submit" class="save btn btn-default">Save</button>
                <a href="{% url 'profile' %}" class="btn btn-default">Cancel</a>
            </form>
        </div>
    </div>
    <script>
        // Javascript variables
        var csrf = '{{ csrf_token }}';
    </script>


{% endblock %}

inventory/templates/items_list.html
{% extends 'base.html' %}
{% block title %}Inventory Management|Items{% endblock %}
{% block content %}
    <h1>Items</h1>
    <table class="table-bordered table-striped">
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Returnable</th>
            <th>Quantity</th>
        </tr>
        {% for item in object_list %}
        <tr>
            <td>{{ item.name }}</td>
            <td>{{ item.description|truncatechars:80 }}</td>
            <td>{% if item.returnable %}Yes{% else %}No{% endif %}</td>
            <td>{{ item.quantity }}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

inventory/templates/provision_by_request.html
{% extends 'base.html' %}
{% block title %}Inventory Management|Provision Item{% endblock %}
{% if messages %}
    {% for message in messages %}
        {{ message }}
    {% endfor %}
{% endif %}
{% block content %}
    <h1>Provision Item By Request</h1>
    <form method="POST" class="item-form">
        {% csrf_token %}
        {{ form.media }}
        <fieldset id="provision-formset">
            <div class="row provision-unit">
                <div class="col-md-3">
                    <label for="id_user">User:</label>
                    <select id="id_user" name="user" disabled class="form-control">
                        <option selected>{{ provision.user.email }}</option>
                    </select>
                </div>
                <div class="col-md-3">
                    <label for="{{ form.item.id_for_label }}">Item</label>
                    {{ form.item.errors }}
                    {{ form.item }}
                </div>
                <div class="col-md-3">
                    <label for="{{ form.return_by.id_for_label }}">Return by</label>
                    {{ form.return_by.errors }}
                    {{ form.return_by }}
                </div>
                <div class="col-md-3">
                    <label for="{{ form.quantity.id_for_label }}">Quantity</label>
                    {{ form.quantity.errors }}
                    {{ form.quantity }}
                </div>
            </div>
        </fieldset>
        <button type="submit" class="save btn btn-default">Save</button>
        <a href="{% url 'dashboard' %}" class="btn btn-default">Cancel</a>
    </form>
{% endblock %}

inventory/templates/provision_item_request.html
{% extends 'base.html' %}
{% block title %}Inventory Management|Provision Item{% endblock %}
{% if messages %}
    {% for message in messages %}
        {{ message }}
    {% endfor %}
{% endif %}
{% block content %}
    <h1>Provision Item By Request</h1>
    <form method="POST" class="item-form">{% csrf_token %}
        <p>
            <label for="id_item">User:</label>
            <select id="id_item" name="item" disabled>
                <option selected>{{ provision.user.email }}</option>
            </select>
        </p>
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
        <a href="{% url 'dashboard' %}" class="btn btn-default">Cancel</a>
    </form>
{% endblock %}